name = "event_display_refresh"
main = "src/index.ts"
compatibility_date = "2022-09-26"

[[queues.producers]]
  queue = "event_display_refresh"
  binding = "QUEUE"

[[queues.consumers]]
  queue = "event_display_refresh"
  max_batch_size = 10   # Max messages per batch
  max_batch_timeout = 1 # Max seconds to wait before batch is full
  max_retries = 3       # Max retries per batch